### ISSUE TITLE
Allowing download for whole albums/playlists at once

### ISSUE THREAD

**Issue by bohrium272** [mayank26saxena/GaanaBot#1]
Just an idea. Would be a great feature.

**Comment by mayank26saxena** [comment]
Sounds good. I will try to incorporate it. Future goals include:
An inline keyboard for choosing option between -
1) Song 2) Album 3) Lyrics
Choosing (1) will let user download one song
(2) Will allow user to download multiple songs at once
(3) User can enter name of song and find lyrics.

**Comment by bohrium272** [comment]
May I work on (3) ?😁. Or any one of the above ?

**Comment by mayank26saxena** [comment]
I'm almost done with 3. You can start with (2).

**Comment by bohrium272** [comment]
OK.
