### ISSUE TITLE
there might be some error, bcoz it's not working

### ISSUE THREAD

**Issue by amarlearning** [mayank26saxena/GaanaBot#2]
![issue](https://cloud.githubusercontent.com/assets/9383897/14905529/2159f1ba-0dcf-11e6-95f7-9cf2cecad215.png)

**Comment by mayank26saxena** [comment]
Currently, GaanaBot is running completely through my laptop. I don't have any dedicated server space. So, whenever I shut down my system, it stops. 
I switched it on in the morning. I hope you received your song!

**Comment by amarlearning** [comment]
Yup!

**Comment by shauryachawla** [comment]
Whoa man great concept!
Please tell me when you will run your laptop. :)

**Comment by mayank26saxena** [comment]
Haha thanks, man! I haven't run this script for quite a long time now. I will try and deploy it on a server soon.
